# Generated by Django 5.0.6 on 2024-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('personid', models.CharField(db_column='personID', max_length=100, unique=True)),
                ('uuid', models.CharField(db_column='Uuid', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
